force-app/main/default/objects/Object__c/Object__c.object-meta.xml
<CustomObject>
    <label>Object</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object__c/fields/Number_of_Fields__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Fields__c</fullName>
    <description>Number of Fields defined on the object</description>
    <inlineHelpText>Number of Fields defined on the object</inlineHelpText>
    <label>Number of Fields</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ObjectTriggerHandler.cls
public class ObjectTriggerHandler implements TriggerHandler {
    
    public void beforeInsert(List<Object__c> newObjects) {
        
        for(Object__c o : newObjects)
        {
            o.Number_of_Records__c = ObjectAndFieldService.getNumberOfRecordsForObjectWhereFieldNotNull(o.Name, 'Id');
            o = ObjectAndFieldService.getObjectDetails(o);
        }
    }
    public void beforeUpdate(List<Object__c> oldObjects, List<Object__c> newObjects, Map<ID, SObject> oldAccountMap, Map<ID, SObject> newAccountMap) {
        for(Object__c o : newObjects)
        {
            o = ObjectAndFieldService.getObjectDetails(o);
            
            o.Number_of_Records__c = ObjectAndFieldService.getNumberOfRecordsForObjectWhereFieldNotNull(o.Name, 'Id');
            
            o.Number_of_Fields__c = ObjectAndFieldService.getFieldCountForObject(o.Name);
        }
    }
    public void beforeDelete(List<Object__c> oldAccounts, Map<ID, SObject> oldAccountMap) {
        
    }
    public void afterInsert(List<Object__c> newAccounts, Map<ID, SObject> newAccountMap) {
        
    }
    public void afterUpdate(List<Object__c> oldAccounts, List<Object__c> newAccounts, Map<ID, SObject> oldAccountMap, Map<ID, SObject> newAccountMap) {
        
    }
    public void afterDelete(List<Object__c> oldAccounts, Map<ID, SObject> oldAccountMap) {
    }
    public void afterUndelete(List<Object__c> newAccounts, Map<ID, SObject> newAccountMap) {
        
        
    }
    
    
}