force-app/main/default/objects/Field__c/Field__c.object-meta.xml
<CustomObject>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Field__c/fields/Number_of_Records_Populated__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Records_Populated__c</fullName>
    <label>Number of Records Populated</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__c</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Object__c/Object__c.object-meta.xml
<CustomObject>
    <label>Object</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FieldTriggerHandler.cls
public class FieldTriggerHandler implements TriggerHandler {
    
    
    
    public void beforeInsert(List<Field__c> newObjects) {
        
        updateFieldUsageCounts(newObjects);
    }
    public void beforeUpdate(List<Field__c> oldObjects, List<Field__c> newObjects, Map<ID, SObject> oldAccountMap, Map<ID, SObject> newAccountMap) {
       updateFieldUsageCounts(newObjects);
    }
    public void beforeDelete(List<Field__c> oldAccounts, Map<ID, SObject> oldAccountMap) {
        
    }
    public void afterInsert(List<Field__c> newAccounts, Map<ID, SObject> newAccountMap) {
        
    }
    public void afterUpdate(List<Field__c> oldAccounts, List<Field__c> newAccounts, Map<ID, SObject> oldAccountMap, Map<ID, SObject> newAccountMap) {
        
    }
    public void afterDelete(List<Field__c> oldAccounts, Map<ID, SObject> oldAccountMap) {
    }
    public void afterUndelete(List<Field__c> newAccounts, Map<ID, SObject> newAccountMap) {
        
        
    }
    
    
    public static void updateFieldUsageCounts(List<Field__c> newObjects)
    {
        
        Map<Id, Object__c> objectDetails = New Map<Id, Object__c>([SELECT Id, Name FROM Object__c]);
        
        for(Field__c f : newObjects)
        {
                        Object__c relatedObject = objectDetails.get(f.Object__c);
            f = ObjectsAndFields.getFieldDetails(f, relatedObject.Name);

       		f.Number_of_Records_Populated__c = ObjectsAndFields.getNumberOfRecordsForObjectWhereFieldNotNull(relatedObject.Name, f.Name);
            
             
            
        }
    }
    
    
    
}