force-app/main/default/objects/Field__c/Field__c.object-meta.xml
<CustomObject>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Field__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__c</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Object__c/Object__c.object-meta.xml
<CustomObject>
    <label>Object</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FieldTriggerHandlerTest.cls
@isTest
private class FieldTriggerHandlerTest {

    @TestSetup
    static void insertTestData(){
        Object__c obj = new Object__c(Name = 'Account');
        insert obj;
    }

    @isTest
    private static void insertRecord()
    {
        Object__c accountObject = [SELECT Id FROM Object__c WHERE Name = 'Account' LIMIT 1];
        Field__c f = new Field__c(Name = 'Name', Object__c = accountObject.Id);
        Insert f;
        System.assertNotEquals(f.Id, Null, 'Field Record Insert Failed');
    }
}