force-app/main/default/objects/Field__c/Field__c.object-meta.xml
<CustomObject>
    <label>Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Field__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__c</referenceTo>
    <relationshipLabel>Fields</relationshipLabel>
    <relationshipName>Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Field__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_Schema_DisplayType.htm</description>
    <inlineHelpText>https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_Schema_DisplayType.htm</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>address</fullName>
            </value>
            <value>
                <fullName>anytype</fullName>
            </value>
            <value>
                <fullName>base64</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Combobox</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>DataCategoryGroupReference</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>DateTime</fullName>
            </value>
            <value>
                <fullName>Double</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>EncryptedString</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Long</fullName>
            </value>
            <value>
                <fullName>MultiPicklist</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Reference</fullName>
            </value>
            <value>
                <fullName>String</fullName>
            </value>
            <value>
                <fullName>TextArea</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Object__c/Object__c.object-meta.xml
<CustomObject>
    <label>Object</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object__c/fields/Number_of_Fields__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Fields__c</fullName>
    <description>Number of Fields defined on the object</description>
    <inlineHelpText>Number of Fields defined on the object</inlineHelpText>
    <label>Number of Fields</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ObjectAndFieldService.cls
public class ObjectAndFieldService {
    
    public static final Map<String, Schema.SObjectType> DESCRIBEOBJECTS;
    static{
        DESCRIBEOBJECTS = Schema.getGlobalDescribe(); 
    }
    
    public static final Map<String, Object__c> OBJECTS;
    static{
        OBJECTS = New Map<String, Object__c>();
        For(Object__c obj : [SELECT Id, Name FROM Object__c])
        {
            OBJECTS.put(obj.Name, obj);
        }
    }
    
    public static void getAndInsertAllObjectsFromSchema(Boolean createable)
    {
        List<Object__c> objects = new List<Object__c>();
        for(Schema.SObjectType d : DESCRIBEOBJECTS.values())
        {
            Schema.DescribeSObjectResult ds = d.getDescribe();
            if(ds.isCreateable() == createable)
            {
                Object__c obj = new Object__c(Name = ds.name);
                objects.add(obj);
            }
        }
        insert objects;
    }
    
    public static void getFieldsForObject(string objName)
    {            
        
        Schema.DescribeSObjectResult r1 = DESCRIBEOBJECTS.get(objName).getDescribe();   
        
        Object__c objectRecord = OBJECTS.get(objName);
        
        if(objectRecord == NULL)
        {
            Object__c newObjectRecord = new Object__c(Name = r1.getName());
            insert newObjectRecord;
            objectRecord = newObjectRecord;
        }
        
        
        List<Field__c> fields = new List<Field__c>();
        
        Map<String , Schema.SObjectField > mapFieldList = r1.fields.getMap();    
        for ( Schema.SObjectField field : mapFieldList.values() ) {    
            Schema.DescribeFieldResult fieldResult = field.getDescribe();    
            
            System.debug(fieldResult.getName());
            Field__c f = new Field__c();
            f.Name = fieldResult.getName();
            f.Label__c = fieldResult.getLabel();
            f.Type__c = String.valueOf(fieldResult.getType());
            f.Object__c = objectRecord.Id;
            fields.add(f);
            
        }
        
        List<Database.SaveResult> insertResults = Database.insert(fields, false);
    }
    
    
    public static object__c getObjectDetails(object__c obj)
    {
        if(obj.Name != Null)
        {        Schema.SObjectType objectType = Schema.getGlobalDescribe().get(obj.Name);
            Schema.DescribeSObjectResult schemaObject = objectType.getDescribe();       
            obj.Label__c = schemaObject.getLabel();
            obj.Custom__c = schemaObject.isCustom();
            obj.Number_of_Fields__c = schemaObject.fields.getMap().values().size();  
        }   
        return obj;  
    }
    
    public static field__c getFieldDetails(field__c f, string objectName)
    {
        if((f != null) && (objectName != null))
        {
            Schema.DescribeSObjectResult objectDetails = DESCRIBEOBJECTS.get(objectName).getDescribe();   
            Schema.SObjectField fieldDetails = objectDetails.fields.getMap().get(f.name);
            
            Schema.DescribeFieldResult fieldResult = fieldDetails.getDescribe();    
            if ( fieldResult.isAccessible() ) {    
                System.debug(fieldResult.getName());
                f.Name = fieldResult.getName();
                f.Label__c = fieldResult.getLabel();
                f.Type__c = String.valueOf(fieldResult.getType());
                f.Custom__c = fieldResult.isCustom();
            }
        }
        return f;
    }
    
    
    public static integer getFieldCountForObject(string objName)
    {           
        if(OBJECTS.containsKey(objName))
        { 
            integer numberOfFields;
            try{
                numberOfFields = DESCRIBEOBJECTS.get(objName).getDescribe().fields.getMap().values().size();   
            }
            catch(Exception e)
            {
                numberOfFields = Null;
            }
            return numberOfFields;
        }
        return Null;
    }
    
    public static integer getNumberOfRecordsForObjectWhereFieldNotNull(string objectName, string fieldName)
    {    
        try{
            AggregateResult[] groupedResults = Database.query('SELECT COUNT(Id)recordCount FROM ' + objectName + ' WHERE ' + fieldName + ' != NULL');
            return Integer.valueOf(groupedResults[0].get('recordCount'));
        }
        catch(Exception e)
        {
            return null;
        }
    }
    
}